name: flexjaransvar
on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 5'
jobs:
  flexjaransvar:
    name: flexjaransvar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run flexjaransvar
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
