name: Stale pull requests
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 13 * * 1'
jobs:
  stale-pull-requests:
    name: Stale pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./hent-repoer.sh
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: npm run security-advisories
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
          FLEX_DEV_WEBHOOK: ${{ secrets.FLEX_DEV_WEBHOOK }}
